version: "3.7"
services:
  ui:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${PORT}:8080"
      - "443:443"
    volumes: 
      - ./secrets:/etc/nginx/secrets
    environment: 
      REACT_APP_API_URL: ${REACT_APP_API_URL}
